# Generated by Django 5.0.6 on 2024-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='browseRecipes')),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('ingredients', models.CharField(max_length=800)),
                ('instructions', models.CharField(max_length=200)),
                ('nutritional_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
