# Generated by Django 5.0.6 on 2024-09-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_alter_browserecipe_allergic_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('phoneno', models.CharField(max_length=15)),
                ('msg', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
