# Generated by Django 5.0.6 on 2024-09-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('feedback_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('issue', 'Problem/Issue'), ('praise', 'Praise/Compliment'), ('general', 'General Question')], max_length=10)),
                ('details', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('recommend', models.BooleanField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
