# Generated by Django 5.0.6 on 2024-09-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0011_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
