# Generated by Django 5.0.6 on 2024-09-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0013_favoriterecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteRecipe',
        ),
    ]
