# Generated by Django 5.0.6 on 2024-09-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0014_delete_favoriterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergic_info',
            field=models.CharField(default='No info', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.CharField(default='No info', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.CharField(default='No info', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='No info', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooktime',
            field=models.CharField(default='No info', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats',
            field=models.CharField(default='No info', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='No info', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction1',
            field=models.CharField(default='No info', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction2',
            field=models.CharField(default='No info', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction3',
            field=models.CharField(default='No info', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.CharField(default='No info', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serve',
            field=models.CharField(default='No info', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='taste',
            field=models.CharField(default='No info', max_length=100),
        ),
    ]
