# Generated by Django 5.0.6 on 2024-09-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0016_alter_recipe_allergic_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browserecipe',
            name='allergic_info',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='browserecipe',
            name='calories',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='browserecipe',
            name='carbohydrates',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='browserecipe',
            name='cooktime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='browserecipe',
            name='fats',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='browserecipe',
            name='instruction1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='browserecipe',
            name='instruction2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='browserecipe',
            name='instruction3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='browserecipe',
            name='protein',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='browserecipe',
            name='serve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='browserecipe',
            name='taste',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbohydrates',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooktime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instruction1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instruction2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instruction3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='taste',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
