# Generated by Django 5.0.6 on 2024-09-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0018_ingredient_cart_cartitem_cart_ingredients_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredient_images/'),
        ),
    ]
