# Generated by Django 5.0.6 on 2024-11-25 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0023_cookingschedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookingschedules',
            old_name='schedule_time',
            new_name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='cookingschedules',
            name='recipe',
        ),
        migrations.AddField(
            model_name='cookingschedules',
            name='meal_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vege.mealplanner'),
        ),
    ]
